### ISSUE TITLE
Help: iOS il2cpp builds not finding dlls

### ISSUE THREAD

**Issue by realworld666** [jilleJr/Newtonsoft.Json-for-Unity#11]
### Behavior

My app will not compile on iOS il2pp when code referencing this plugin is used in an assembly definition. The code compiles fine in the editor and on Android platform.
Assets/Plugins/TUB/Model/AppVersion.cs(17,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

### Steps to reproduce

- New project
- Import `jillejr.newtonsoft.json-for-unity` via UPM
- Switch to iOS platform
- Create some code referencing the plugin
- Create an assembly definition that includes this code
![image](https://user-images.githubusercontent.com/284881/68206435-92053b00-ffc4-11e9-8bbc-b3362ada284e.png)
- Build for iOS

### Details

Host machine OS running Unity Editor 👉 MacOS 10.6.3

Target platform running build 👉 iOS

Newtonsoft.Json-for-Unity package version 👉 12.0.1

Using Unity version 👉 Unity 2018.4.12f1

### Checklist

- [x ] Shutdown Unity, deleted the /Library folder, opened project again in Unity, and problem still remains.
- [x ] Checked to be using latest version of the package.

**Comment by jilleJr** [comment]
Hi Dave!

This was fixed in `12.0.1-patch-001`

Sorry for the inconvenience but the latest package version is kind of hidden and does not show in Unity's package manager view. The latest version is `12.0.1-patch-001`, and not `12.0.1`.

> ### Updating manually via the manifest file
>
> Change the version field. You have to know the new version beforehand.
>
> Example, with this as old:
>
> ```json
> {
>   "dependencies": {
>     "jillejr.newtonsoft.json-for-unity": "12.0.1"
>   }
> }
> ```
>
> New, updated:
>
> ```json
> {
>   "dependencies": {
>     "jillejr.newtonsoft.json-for-unity": "12.0.1-patch-001"
>   }
> }
> ```
>
> _Omitted `scopedRegistries` and Unity packages for readability_
>
> _Taken from: <https://github.com/jilleJr/Newtonsoft.Json-for-Unity/blob/master/README.md#updating-manually-via-the-manifest-file>_
