### ISSUE TITLE
JsonSerializationException

### ISSUE THREAD

**Issue by jayp84847** [jilleJr/Newtonsoft.Json-for-Unity#127]
I am using json in my unity project. Everything works good in unity editor. 

But when I build it for android it shows me this error.

Please guide me in it.

![20210518_191940](https://user-images.githubusercontent.com/81388248/118710431-e5a04800-b83b-11eb-9fa5-284c080f17d7.png)
![20210518_191956](https://user-images.githubusercontent.com/81388248/118710449-ec2ebf80-b83b-11eb-85bb-e2cdfb4e3a9d.png)

This is the code

```cs
DeepAI_API api = new DeepAI_API(apiKey: "quickstart-QUdJIGlzIGNvbWluZy4uLi4K");

StandardApiResponse resp = api.callStandardApi("torch-srgan", new {
        image = File.OpenRead("C:\\path\\to\\your\\file.jpg"),
});
```

**Comment by jilleJr** [comment]
Hi @jayp84847! Thanks for reaching out!

At first glance my guess is that the error originates from the code stripping that Unity does on some platforms. My guess is that `api.callStandardApi` does something like `JsonConvert.DeserializeObject<StandardApiResponse>(responseBody)`, and so given that, adding something like the following should resolve your issue:

```cs
// Save this somewhere inside your Assets folder
// No need to add it to the scene, it just needs to be included
// in the compilation
using Newtonsoft.Json.Utilities;
using UnityEngine;
 
public class AotTypeEnforcer : MonoBehaviour
{
    public void Awake()
    {
        AotHelper.EnsureType<DeepAI.StandardApiResponse>();
    }
}
```

In short: Unity trims aways some methods, constructors, properties, and types that it thinks are unused, just to trim down the build size. Unity does not understand it needs to keep the constructors of the types when deserializing.

You can read more on this here:

- What is AOT and why do you need to care? https://github.com/jilleJr/Newtonsoft.Json-for-Unity/wiki/What-even-is-AOT
- Wiki on AotHelper: https://github.com/jilleJr/Newtonsoft.Json-for-Unity/wiki/Fix-AOT-using-AotHelper
- Reference docs on `AotHelper.EnsureType<T>()`: https://github.com/jilleJr/Newtonsoft.Json-for-Unity/wiki/Reference-Newtonsoft.Json.Utilities.AotHelper#aothelperensuretype

**Comment by jayp84847** [comment]
Thats good it solve my error but still its not working in android can you
guide me for it. After this solution I debug apk and there are no errors
but still no result is coming. In debug it shows
output_url(which I want) = null

Can you help me?:)

**Comment by jilleJr** [comment]
Sounds like Unity is trimming away your properties as well.

Instead of using AotHelper, you could try adding a `link.xml` file instead.

Add this file somewhere inside your Assets folder. The name must be `link.xml` (must be lower-cased)

```xml
<linker>
    <!-- Assuming here your assembly name is DeepAI -->
    <assembly fullname="DeepAI">
        <type fullname="DeepAI.StandardApiResponse" />
    </assembly>
</linker>
```

Further reading on `link.xml` files: https://github.com/jilleJr/Newtonsoft.Json-for-Unity/wiki/Fix-AOT-using-link.xml

**Comment by jayp84847** [comment]
Dammmmmm!!!!! Really really thank you so much. Thank you its working now.
☺️☺️😊😊

**Comment by jilleJr** [comment]
Glad to help :)
