### ISSUE TITLE
Namespace "Newtonsoft.Json" is undefined

### ISSUE THREAD

**Issue by andreyshade** [jilleJr/Newtonsoft.Json-for-Unity#128]
I can't use the library in my project's scripts because namespace "Newtonsoft.Json" undefined. May be I miss something during the installation of package. Any suggestion?

**Comment by jilleJr** [comment]
If you're using custom assembly definitions then make sure to either automatically reference assemblies in it or add the Newtonsoft.Json assembly in manually.

If you're not using custom assembly definitions, then I need more context, perhaps a reproducible sample

**Comment by andreyshade** [comment]
I'm trying to avoid using asmdefs. Is there any solution to deal with this issue without assembly definitions?

**Comment by jilleJr** [comment]
If not using asmdefs then the assembly should be loaded by default.

Are you experiencing then when building or when using the editor?

Could you post the full error message?

**Comment by andreyshade** [comment]
I have dealt with my issue it was a wrong version of  Newtonsoft.Json in  packages.config file 
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/10078161/120371753-edbdb480-c31e-11eb-87a7-7e4492f83038.png">
And it works properly now, thank you for your support

**Comment by jilleJr** [comment]
No! Don't hesitate on asking further questions.

I'm closing this issue as resolved tho.
