### ISSUE TITLE
Assembly version conflict

### ISSUE THREAD

**Issue by jakeobrien** [jilleJr/Newtonsoft.Json-for-Unity#129]
I am getting the following error in my Unity console:
```
Assembly 'Library/ScriptAssemblies/MyProject.dll' will not be loaded due to errors:
MyProject references strong named Newtonsoft.Json Assembly references: 10.0.0.0 Found in project: 13.0.0.0.
```

I deleted my Library folder and all the .csproj files to let Unity rebuild them. I can't find any references to Newtonsoft.Json in any of the .csproj files. (Not sure how to check .dlls.) I had the JamesNK plugin in the project previously, but it should be completely removed. 

Not sure what is referencing the older version or how to find it. 

I'm using Unity 2020.3.6. and the latest version of this plugin 13.0.102. 

Any help would be appreciated!

**Comment by jilleJr** [comment]
Hi @jakeobrien! If that is your error word for word, then you need to seek your project after a file named `MyProject.dll`.
It could be placed in Assets or Packages folder. 

I have backported this repo even to v10, so if you actually need Newtonsoft.Json v10 then you can change the package version to 10.0.302

**Comment by jakeobrien** [comment]
@jilleJr Thanks for the quick response! I can't find any sign of a reference to any version of Newtonsoft.Json other than v13 in that dll or anywhere. 🤷

But i rolled back to v10 per your request and it works now, so thank you!
