### ISSUE TITLE
Document incompatibility with `com.unity.nuget.newtonsoft-json`

### ISSUE THREAD

**Issue by jilleJr** [jilleJr/Newtonsoft.Json-for-Unity#141]
>The `com.unity.nuget.newtonsoft-json` version 2.0.0 and above has clashing GUIDs for the Unity assets, as mentioned by #139 and https://github.com/jilleJr/Newtonsoft.Json-for-Unity/discussions/135.
>
>Unity did not regenerate the GUIDS when they forked my package, and so now my package cannot coexist with theirs.
>
>Then there's the DLL and namespace issue: Only one Newtonsoft.Json.dll assembly and only one Newtonsoft.Json namespace can be imported at the same time.

*^Copied from #140*

The above needs to be mentioned in the README. But phrased in a more clear way and perhaps more IN-YOUR-FACE to force the focus of the reader

**Comment by MartinHaeusler** [comment]
@jilleJr I just bumped into this problem when I tried to upgrade to Unity 2020.3.24f1 (LTS). I've been using your package very successfully, but Unity refuses to compile with it in this particular version.

What's the upshot here? Is it ok to use Unity's own version? Does it do the same thing, do we configure it the same way (especially with respect to AOT concerns)?

**Comment by jilleJr** [comment]
@MartinHaeusler Excellent question!

Short answer is that it's fully OK to use Unity's version, because it's a fork of this/my repo, albeit an outdated version. Mine and Unity's fork are sadly heavily incompatible. Only one of them can live in a Unity project at the same time.

Long answer:

> I'm in the middle of a negotiation with Unity to officially adopt my package or not. They did fork my repo before and used their fork in some of their internal packages, leading to some issues such as Unity assets GUIDs and C# namespace collisions. This conversation has been going on for maybe two years now and currently the milestone for an "official adoption" of this repo is for the Unity 2022 release, altough this is not certain as they are not that keen in having to support a third-party package, even with my help.
> 
> The latest tip I can give is that if you're using a package that already references Unity's fork of my repo, namely [`com.unity.nuget.newtonsoft-json@2.0`](https://docs.unity3d.com/Packages/com.unity.nuget.newtonsoft-json@2.0/manual/index.html), then stick with that one. It's based off the `v12.0.101` tag of this repo if I'm not misstaken.
> 
> /.../
>
> https://github.com/jilleJr/Newtonsoft.Json-for-Unity/issues/133#issuecomment-908933660

I've answered this in other places as well. Maybe you'll find more context there:

- https://github.com/jilleJr/Newtonsoft.Json-for-Unity/discussions/135#discussioncomment-1208499

**Comment by MartinHaeusler** [comment]
@jilleJr thanks for the quick response! Oh wow that's a mess 😅  I'm not even sure where the dependency to the unity-flavour of your package is coming from in the first place. The package manager doesn't even show it. Dependency management in general is such a major pain in Unity, because there isn't just one place to look at, but rather like 5, in different formats. Well, for the time being that means I'm stuck with the older unity version. Which is fine I guess. I just did a `git reset --hard` to revert the upgrade, but something is still wrong... argh. Unity. why... xD

**Comment by jilleJr** [comment]
@MartinHaeusler My go-to answer for when Unity behaves is to close it down, delete the Library folder, and then start it back up again. This clears all compilation caches, among other things.

It does mean everything is reimported again. So if you have for example lots of videos you've transcoded in Unity (such as changing their resolution), those will get re-transcoded.

**Comment by MartinHaeusler** [comment]
@jilleJr yes that's what I ended up doing, after panicking for a minute. Things seem to be back to normal. I'll stay on 2020.2 until things get sorted out. I just hope I won't hit any severe Unity bugs that would force me to upgrade. Thank you for your efforts and advice, as always.

**Comment by jilleJr** [comment]
Added notice to README.md and have written up a new pinned issue. Closing
