### ISSUE TITLE
Problem in a DLL, hard to debug

### ISSUE THREAD

**Issue by jelmerS2** [jilleJr/Newtonsoft.Json-for-Unity#144]
I'm using a DLL [Q42.HueApi](https://github.com/Q42/Q42.HueApi) (source is available there) and am now using Newtonsoft.Json-for-Unity.
In Unity everything works fine. 
On UWP (x64 or ARM64, happens on both), I encouter errors with no useful stacktrace. I tried everything I know (copy PDB files, including PDB files form the DLLs in VS + script debugging, all in debug mode of course), but can't get more info for now..

The error is:
```
Exception thrown at 0x00007FFB0FAA4F69 in HL2HUE.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x000000E7B01FCCC0.
Value cannot be null.
Parameter name: source
```

This happens in client.GetLightsAsync(); 
```cs
                    try
                    {
                        Debug.Log("try get lights");
                        lights = await client.GetLightsAsync();
                        Debug.Log("finished try het lights");
                    }
                    catch (Exception e)
                    {
                        Debug.LogError(e.Message);
                    }
```

In the [source ](https://github.com/Q42/Q42.HueApi/blob/master/src/Q42.HueApi/HueClient-Lights.cs)for that DLL; this is what that method looks like:

```cs
public async Task<IEnumerable<Light>> GetLightsAsync()
    {
      CheckInitialized();

      HttpClient client = await GetHttpClient().ConfigureAwait(false);
      string stringResult = await client.GetStringAsync(new Uri(String.Format("{0}lights", ApiBase))).ConfigureAwait(false);

      List<Light> results = new List<Light>();

      JToken token = JToken.Parse(stringResult);
      if (token.Type == JTokenType.Object)
      {
        //Each property is a light
        var jsonResult = (JObject)token;

        foreach (var prop in jsonResult.Properties())
        {
          Light? newLight = JsonConvert.DeserializeObject<Light>(prop.Value.ToString());
          if (newLight != null)
          {
            newLight.Id = prop.Name;
            results.Add(newLight);
          }
        }
      }
      return results;
    }
```

I suspect something is going wrong with deserialization, but I don't know how to find out more. 

To avoid problems with code stripping, I tried to simply include everything by doing so:
```xml
<linker>
    <assembly fullname="Q42.HueApi" preserve="all"/>
  <assembly fullname="Q42.HueApi">
    <type fullname="Q42.HueApi.NuPnPResponse" />
    <type fullname="Q42.HueApi.Light" />
  </assembly>
  <assembly fullname="Q42.HueApi.ColorConverters" preserve="all"/>
  <assembly fullname="Newtonsoft.Json" preserve="all"/>
</linker>
```
Not sure if that is enough.

Any thoughts on what the problem might be? Or how to debug better?

**Comment by jelmerS2** [comment]
OK! So using Exception.InnerException I was able to get:

Attempting to call method 'Newtonsoft.Json.Utilities.CollectionWrapper`1[[System.Double, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5619xxxxxx]]::.ctor' for which no ahead of time (AOT) code was generated.

That makes it more clear..

**Comment by jelmerS2** [comment]
This is the line where it goes wrong: 
```
          Light? newLight = JsonConvert.DeserializeObject<Light>(prop.Value.ToString()); ``` 

I added this but that didn't solve it?
```
AotHelper.EnsureList<Q42.HueApi.Light>(); ```

**Comment by jilleJr** [comment]
Hello @jelmerS2! Thanks for researching further. Hectic life lead me to not want to tackle this right now, but that error message is fairly straight forward (from my perspective, as I recognize it a lot).

There's different ways around resolving this. For this particular case, as the source code is using JToken.Parse, it gets a little tricky. But the following should at least bring you onwards:

```cs
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Utilities;
using UnityEngine;
using Q42.HueApi;

// Does not need to be added to a GameObject in a scene.
// It only needs to live inside your Assets directory.
// Inheriting from MonoBehaviour ensures it will get compiled,
// then AotHelper ensures types further.

public class AotEnsure : MonoBehaviour
{
    private void Awake()
    {
        AotHelper.EnsureList<Light>();
    }
}
```

Reference: https://github.com/jilleJr/Newtonsoft.Json-for-Unity/wiki/Reference-Newtonsoft.Json.Utilities.AotHelper#aothelperensurelist

**Comment by jilleJr** [comment]
> This is the line where it goes wrong:
> 
> ```
>           Light? newLight = JsonConvert.DeserializeObject<Light>(prop.Value.ToString()); 
> ```
> 
> I added this but that didn't solve it?
> 
> ```
> AotHelper.EnsureList<Q42.HueApi.Light>(); 
> ```

In the exception you got, namely:

> Attempting to call method 'Newtonsoft.Json.Utilities.CollectionWrapper`1[[System.Double, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5619xxxxxx]]::.ctor' for which no ahead of time (AOT) code was generated.

it states that it's actually failing to deserialize the type `Newtonsoft.Json.Utilities.CollectionWrapper<double>`, albeit with its not-so-clear syntax.

I found that `LightCommand` contains a reference to a list of `double`'s: https://github.com/Q42/Q42.HueApi/blob/v3.18.1/src/Q42.HueApi/Models/LightCommand.cs#L22
That is probably what messes this up.

There's a distinction in IL2CPP how it handles generic types of value types (eg `double`, `decimal`, `DateTime`) vs reference types (eg `string` or any other `class`). I've do not seem to have written about this in the wiki, otherwise I would point you there. But if you want to dig into the topic, I would recommend reading Unity's blog post on the matter: https://blog.unity.com/technology/il2cpp-internals-generic-sharing-implementation

Hope this helps!

**Comment by jelmerS2** [comment]
Thanks so much again! Adding the AotHelper.EnsureList<double>(); did the trick!
