### ISSUE TITLE
Cleanup issue templates

### ISSUE THREAD

**Issue by jilleJr** [jilleJr/Newtonsoft.Json-for-Unity#57]
They contain way too many sections, and the bug reporting doesn't even contain a "description" section. Currently they are kind of just in the way instead of helping

GitHub already links to the code of conduct, don't need to repeat that as a comment

If anyone except me reads this, then please comment any suggestions on which types of templates you think are missing.

**Comment by tsira** [comment]
I think the two you have are good, can limit it to feature requests and bug reports. Maybe add one for PRs?

**Comment by tsira** [comment]
Maybe you could differentiate the New Features as Doc Updates, Example Updates, Code / Feature Updates?

**Comment by jilleJr** [comment]
@tsira Thanks! Those are some solid ideas! :)

Will explore the idea of adding PR templates. Haven't used those before. You've a nice list there of PR template suggestions
