### ISSUE TITLE
Bug: fails to connect to the UPM registry

### ISSUE THREAD

**Issue by laurentopia** [jilleJr/Newtonsoft.Json-for-Unity#64]
![image](https://user-images.githubusercontent.com/26075468/88640923-5ee36a00-d073-11ea-8811-af19080f41a7.png)
the manifest seems correct for 2018.4.25
`{
	"scopedRegistries": [
		{
			"name": "Packages from jillejr",
			"url": "https://npm.cloudsmith.io/jillejr/newtonsoft-json-for-unity/",
			"scopes": [
				"jillejr"
			]
		}
	],
  "dependencies": {
	  "jillejr.newtonsoft.json-for-unity": "12.0.201",
    "com.unity.analytics": "3.2.3",
    "com.unity.collab-proxy": "1.2.15",
    "com.unity.package-manager-ui": "2.0.13",
    "com.unity.textmeshpro": "1.4.1",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}
`

**Comment by laurentopia** [comment]
found the solution in this issue https://github.com/jilleJr/Newtonsoft.Json-for-Unity/issues/59
thank you

**Comment by jilleJr** [comment]
Thanks for making time reporting issues!
Nice to see you already found a solution ^^ kudos for looking for related issues!
