### ISSUE TITLE
Only install json-for-unity (Newtonsoft.Json) into specific assembly

### ISSUE THREAD

**Issue by rdcm** [jilleJr/Newtonsoft.Json-for-Unity#75]
Hi!

In my unity project, I have several assemblies, in "Contracts" defined interfaces and concrete implementations in "Impl".
After installation package `json-for-unity` visible for all assemblies. Could I restrict visibility for this package? Would be perfect if this code:

```
var json = JsonConvert.SerializeObject("....");
```

 will be compiled only in "Impl" assembly.

**Comment by jilleJr** [comment]
@rdcm Why yes you can!

Given you have your two assemblies as assembly definitions (.asmdef) in your Unity project, there is a setting on those definition files to only reference specific assemblies.

By default, your assembly definition will reference all assemblies loaded into the project. But you can disable this by toggling "Override References"

> ![image](https://user-images.githubusercontent.com/2477952/104852361-f1fead80-58fa-11eb-9e73-796d8655bb6c.png)
>
> Screenshot taken from Unity 2019.4.2f1. In older/newer versions, the setting may be named differently.

By enabling the "Override References" setting, a new setting appears: the "Assembly References" list.

With the list empty, it won't reference this package's Newtonsoft.Json assembly. The following script does not compile:

```cs
using UnityEngine;

public class ContractsScript : MonoBehaviour
{
    void Start()
    {
        var json = Newtonsoft.Json.JsonConvert.SerializeObject("....");
    }
}
```

```
Assets\Contracts\ContractsScript.cs(10,20): error CS0103: The name 'Newtonsoft' does not exist in the current context
```

If your assembly still relies on other assemblies, you can of course add them manually.

There's no way to only blacklist the Newtonsoft.Json assembly and still automatically reference all other assemblies though.

**Comment by rdcm** [comment]
@jilleJr Thanks for the answer, you save my day.

But for example, extenject provides a more simple way for including dependencies into the project.
![image](https://user-images.githubusercontent.com/11910763/104853579-d8696000-5912-11eb-9aed-1b0bda8fba56.png)

As you can see in `Assembly Definition References` explicit reference to zenject and without this ref I get a compile error. No need to enable Override References.

Is it possible to provide the same mechanism for including dependencies?

**Comment by jilleJr** [comment]
@rdcm Unity sadly handles precompiled assemblies (.DLL's) and assembly definitions (.asmdef) very differently.

As asmdef are only whitelist and assemblies are by default always loaded but optionally opt in to whitelist, I do not see issue here.

I won't refactor Newtonsoft.Json to work as an asmdef due to a lot of reasons (some of which: It's a ton of source code, faster and smaller in size to deliver as a DLL. It's a ton of code to refactor. It works as-is).

By using the "Override References" list, you should be able to get the same level of control on your loaded assemblies. Just that you'd have to work with 2 lists instead of 1.

> ![image](https://user-images.githubusercontent.com/2477952/104854304-2e83d680-5906-11eb-9f57-92ef45fa4690.png)
>
> Image taken from Unity docs: "Assembly definitions / Referencing a precompiled, plugin assembly"
> https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html#reference-precompiled-assembly

**Comment by rdcm** [comment]
Ok, thanks for your answers! 
I close this issue.
