### ISSUE TITLE
Bug: in the page "Install Converters via UPM"

### ISSUE THREAD

**Issue by hadesfury** [jilleJr/Newtonsoft.Json-for-Unity#78]
The installation guideline were misleading

- The "all package scope is not available anymore in unity" -> don’t know how to fix it
- The version number displayed to enter the package version manually is incorrect or has changed -> fix below

It seems that `"jillejr.newtonsoft.json-for-unity.converters": "12.1.0"` should be replaced by `"jillejr.newtonsoft.json-for-unity.converters": "1.0.0"` then the upgrade works as expected

**Comment by jilleJr** [comment]
@hadesfury Thanks for reporting this!

Just to clarify, does this strictly refer to the converters installation, or the newtonsoft.json-for-unity installation?

**Comment by hadesfury** [comment]
I only apply to the converters .. sorry for not being specific enough

**Comment by jilleJr** [comment]
Took me some time to get to it. But it's fixed now. Thanks for reporting this!
